name=FT6236
version=1.0.2
author=Dustin Watts
maintainer=Dustin Watts
sentence=Arduino library for FT6236 capacitive touch controller.
paragraph=Supports FT6236, FT6236U, and FT6206 on ESP32 TouchDown and compatible boards.
category=Display
url=https://github.com/DustinWatts/FT6236
architectures=*
